#!/bin/bash

set -o errexit -o nounset -o pipefail

grep -e "/usr/local/bin/zsh" /etc/shells || true
if [ $? -eq 0 ]; then
    exit 0
fi

echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/zsh

