#!/bin/bash

set -o errexit -o nounset -o pipefail

# check if pipx is installed
if ! command -v pipx &> /dev/null; then
    echo "pipx not found. Installing pipx via Homebrew..."
    brew install pipx
fi

# install pynvim using pipx
pipx install pynvim

# ensure pipx PATH is configured
pipx ensurepath
