# ----------------------------------------
# zsh options
# ----------------------------------------
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt correct
setopt list_packed
setopt no_beep
setopt print_eight_bit
setopt share_history
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt hist_reduce_blanks
setopt noautoremoveslash

# ----------------------------------------
# environment variables
# ----------------------------------------
export INPUTRC="$ZDOTDIR/inputrc"

# ----------------------------------------
# expansions
# ----------------------------------------
source $ZDOTDIR/zsh-plugins
source $ZDOTDIR/functions
source $ZDOTDIR/aliases
source $ZDOTDIR/keybinds

# ----------------------------------------
# development
# ----------------------------------------
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"
eval "$(nodenv init - zsh)"
eval "$(rbenv init -)"

# ----------------------------------------
# 未整理
# ----------------------------------------
